[package]
name = "bazel-broken-dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
cucumber = { version = "0.19.1", features = ["libtest"] }
